### ISSUE TITLE
Option to show only current/backlog

### ISSUE THREAD

**Issue by mhfrantz** [jimlloyd/ya-git-pivotal#9]
Excluding the icebox makes the list of choices a lot shorter.

**Comment by unitive-jim** [comment]
This is possible with the current revision. From the README:

```
	--unstarted
	--unscheduled
	--started
	    If any of these three options are specified, search only for stories of the given states.
	    By default, search for unstarted (backlog) and unscheduled (icebox) stories.
```

See the last line. You can search only the backlog with `git pivotal start --unstarted`.

**Comment by unitive-jim** [comment]
See #12.

**Comment by unitive-jim** [comment]
With v0.1.1 you can now set the default story states to filter with the `pivotal.states` config variable.
